title: RMMR Group Documentation
description: Docs for the RMMR Group
theme: just-the-docs

url: https://rmmr-group.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
